{% set version = "3.1.0" %}

package:
  name: intervaltree
  version: {{ version }}

source:
  fn: intervaltree-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/intervaltree/intervaltree-{{ version }}.tar.gz
  sha256: 902b1b88936918f9b2a19e0e5eb7ccb430ae45cde4f39ea4b36932920d33952d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sortedcontainers

test:
  imports:
    - intervaltree

about:
  home: https://github.com/chaimleib/intervaltree
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Editable interval tree data structure for Python 2 and 3
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
