{% set version = "3.0.0" %}

package:
  name: intervaltree
  version: {{ version }}

source:
  fn: intervaltree-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/intervaltree/intervaltree-{{ version }}.tar.gz
  sha256: 54860d217e257b5d6342ad38a25190ea9da9b9eb9c5444aeca48e46a6e355cb6

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - sortedcontainers
  run:
    - python
    - sortedcontainers

test:
  imports:
    - intervaltree
  requires:
    - pytest

about:
  home: https://github.com/chaimleib/intervaltree
  license: Apache-2.0
  summary: 'Editable interval tree data structure for Python 2 and 3'
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
