{% set version = "3.0.1" %}

package:
  name: intervaltree
  version: {{ version }}

source:
  fn: intervaltree-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/intervaltree/intervaltree-{{ version }}.tar.gz
  sha256: 80204a17c1bd7388f402459bf1528d7dc8f03db42afbde58f265081d25eea62b

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - sortedcontainers
  run:
    - python
    - sortedcontainers

test:
  imports:
    - intervaltree
  requires:
    - pytest

about:
  home: https://github.com/chaimleib/intervaltree
  license: Apache-2.0
  summary: 'Editable interval tree data structure for Python 2 and 3'
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
