{% set version = "3.2.0" %}

package:
  name: intervaltree
  version: {{ version }}

source:
  fn: intervaltree-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/i/intervaltree/intervaltree-{{ version }}.tar.gz
  sha256: f1e83911d63206f145a039a5b03f2e86297814b1e8b5cfba3af6a09f1b9a73d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - sortedcontainers

test:
  imports:
    - intervaltree

about:
  home: https://github.com/chaimleib/intervaltree
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Editable interval tree data structure for Python 2 and 3
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
